### ISSUE TITLE
[REQUEST] Movies support?

### ISSUE THREAD

**Issue by llunawolf** [wolfswolke/aniworld_scraper#30] opened 2023-12-20 19:03 UTC
**Please describe what you want to be added/changed:**
Support for the "Filme" (Movies) tab on Aniworld. It's often used for Specials and Movies (although it's actually mostly specials it seems)
![image](https://github.com/wolfswolke/aniworld_scraper/assets/154262232/32bfd434-9780-4b57-a962-400cb11abb68)

Only the naming of the files might be complicated here because I'm not sure if the order Aniworld has is really trustworthy (in the sense that they might add ones in-between and scramble the order). Maybe just use the titles here? The things on that tab are usually very chaotic anyway, so manual renaming and organization would be needed here anyways.

**Possible Solutions if you have any:**
- Take in "Filme" or similiar for the season field
- Use `/filme` in the URL instead of `/staffel-x`
- Essentially do the same thing as with seasons, but with different file naming.

**Comment by llunawolf** [comment] 2023-12-20 19:05
(If this is already possible, please tell me. I just searched for `/filme` in the code through GitHub and couldn't find anything)
Would contribute myself, but I have no clue about Python.

**Comment by wolfswolke** [comment] 2023-12-25 21:03
@llunawolf you can now use this to download Movies: `python .\main.py anime toradora Ger-Sub True`
The Bool at the end is the Movie Bool. If its true it will download filme/film-X and if its False it will download staffel-X/episode-X
Please test it and tell me if it works.

**Comment by alternone** [comment] 2023-12-26 09:02
Tested and works well. I just started to implement the function as well last evening. Just discovered before your new commit :D

PS: You should check out argparse - that could replace several pieces of your code and also the shell/batch part as it also include checks, defaults, enums and many more.
https://docs.python.org/3/library/argparse.html I use it in nearly all projects at work. It also generated a man page with --help

**Comment by wolfswolke** [comment] 2023-12-26 20:45
Hi @alternone .
I will look into it some day. But currently im using 90% of my spar time to work on the DeathgarenRebirth Project.
If you want you can open a PR or i will implement it once i have some time.

**Comment by llunawolf** [comment] 2023-12-27 21:09
So um, the moving downloading works great, but uh... how do I download non-movies now?

```
python3 "main.py" "anime" "pokmon" "Deutsch" "False" "6"
python3 "main.py" "anime" "pokmon" "Deutsch" "false" "6"
python3 "main.py" "anime" "pokmon" "Deutsch" "True" "6"
python3 "main.py" "anime" "pokmon" "Deutsch" "true" "6"
```
All of these download the movie.

**Comment by wolfswolke** [comment] 2023-12-27 21:26
Temp fix dont use a season override. forgot the logic there...

**Comment by wolfswolke** [comment] 2023-12-27 21:38
Actualy not a me bug!
py just doesnt understand Bools as arguments...
(py310_AniWorldScraper) PS D:\python\projects\AniWorldScraper> python .\main.py anime pokmon Ger-Sub 6
DEBUG:src.constants:cli argument detected on position:1 with value:anime
DEBUG:src.constants:cli argument detected on position:2 with value:pokmon
DEBUG:src.constants:cli argument detected on position:3 with value:Ger-Sub
DEBUG:src.constants:cli argument detected on position:4 with value:6

**Comment by Bramdarl** [comment] 2023-12-28 20:06
> Actualy not a me bug! py just doesnt understand Bools as arguments... (py310_AniWorldScraper) PS D:\python\projects\AniWorldScraper> python .\main.py anime pokmon Ger-Sub 6 DEBUG:src.constants:cli argument detected on position:1 with value:anime DEBUG:src.constants:cli argument detected on position:2 with value:pokmon DEBUG:src.constants:cli argument detected on position:3 with value:Ger-Sub DEBUG:src.constants:cli argument detected on position:4 with value:6

this should help:
`movie = (parse_cli_arguments(False, 4).lower() == 'true')  # True = movie. False = episode`

**Comment by wolfswolke** [comment] 2023-12-28 20:12
@llunawolf Can you please try if the issue is fixed for you as well?
Just implemented @Bramdarl fix which worked on my Machine and Test machine.

**Comment by Monokuma11** [comment] 2024-01-22 11:18
![grafik](https://github.com/wolfswolke/aniworld_scraper/assets/75888159/b3d8bf86-e9ee-4211-87fc-61dfd6d9a12d)

I tried the new version with a movie, but got those exceptions in return

**Comment by wolfswolke** [comment] 2024-01-22 11:22
> ![grafik](https://github.com/wolfswolke/aniworld_scraper/assets/75888159/b3d8bf86-e9ee-4211-87fc-61dfd6d9a12d)
> 
> I tried the new version with a movie, but got those exceptions in return

@Monokuma11 you are using the Windows Store version of python. This version is from what I know very buggy and you might need to run the script as admin etc because the permissions are not set correctly sometimes.

**Comment by Monokuma11** [comment] 2024-01-22 11:30
![grafik](https://github.com/wolfswolke/aniworld_scraper/assets/75888159/c51021a5-9c81-4e5b-852a-201411cc44a6)
The error stays :(

**Comment by wolfswolke** [comment] 2024-01-24 20:07
@Monokuma11 please try the latest version which was just merged. (Git clone...) If that still does not work create a new issue please with the Anime Name, Your settings and also the log output.

**Comment by wolfswolke** [comment] 2024-01-26 17:34
Closed. No Response from original creator.

**Closed by wolfswolke** 2024-01-26 17:34 UTC
Labels: enhancement
